!TCL=811, Sahi Narayan Raman
!TITLE=Sahi Keywords
!SORT=Y
!CHARSET=DEFAULT

!TEXT=_include
_include(URL/filePath)
!

!TEXT=_button
_button(id)
!

!TEXT=_submit
_submit(id)
!

!TEXT=_textbox
_textbox(id)
!

!TEXT=_password
_password(id)
!

!TEXT=_checkbox
_checkbox(id)
!

!TEXT=_textarea
_textarea(id)
!

!TEXT=_accessor
_accessor(id)
!

!TEXT=_byId
_byId(id)
!

!TEXT=_select
_select(id)
!

!TEXT=_radio
_radio(id)
!

!TEXT=_image
_image(id)
!

!TEXT=_imageSubmitButton
_imageSubmitButton(id)
!

!TEXT=_link
_link(id)
!

!TEXT=_getSelectedText
_getSelectedText(element)
!

!TEXT=_getCellText
_getCellText(element)
!

!TEXT=_random
_random()
!

!TEXT=_savedRandom
_savedRandom(id)
!

!TEXT=_cell
_cell(id)
!

!TEXT=_table
_table(id)
!

!TEXT=_containsHTML
_containsHTML(element,html)
!

!TEXT=_containsText
_containsText(element,txt)
!

!TEXT=_popup
_popup(id)
!

!TEXT=_event
_event
!


!TEXT=_click
_click(element)
!

!TEXT=_highlight
_highlight(element)
!

!TEXT=_setValue
_setValue(element, value)
!

!TEXT=_setSelected
_setSelected(element, selectedText)
!

!TEXT=_check
_check(element)
!

!TEXT=_wait
_wait(timeInMillis)
!

!TEXT=_simulateEvent
_simulateEvent(event)
!

!TEXT=_setGlobal
_setGlobal(name, value)
!

!TEXT=_getGlobal
_getGlobal(value)
!

!TEXT=_assertNotNull
_assertNotNull(element)
!

!TEXT=_assertNull
_assertNull(element)
!

!TEXT=_assertTrue
_assertTrue(condition)
!

!TEXT=_assertNotTrue
_assertNotTrue(condition)
!

!TEXT=_assertEqual
_assertEqual(object1, object2)
!

!TEXT=_assertNotEqual
_assertNotEqual(object1, object2)
!

!TEXT=_alert
_alert(txt);
!

!TEXT=_eval
_eval(commandString)
!

!TEXT=_call
_call(functionName)
!

!TEXT=_confirm
_confirm(txt)
!

!TEXT=_prompt
_prompt(txt)
!

!TEXT=_log
_log(txt, type)
!

!TEXT=_navigateTo
_navigateTo(url)
!

!TEXT=_dragDrop
_dragDrop(draggableElement, dropDestinationElement)
!

