source 'https://rubygems.org'

gem 'rails', '2.3.18'
gem 'retryable'

gem 'feature_toggle', '~> 0.0.2'
gem 'rake'
gem 'httparty', '~>0.11.0'
gem 'erubis', '~> 2.7.0'
gem 'rails_xss'
gem 'RedCloth', '3.0.4', :require => 'redcloth'
gem 'rack', '~> 1.1.3'
gem 'validatable', '1.6.7'
gem 'mingle_keyvalue_store'
gem 'jruby-openssl', '0.9.21'
gem 'mingle_macro_models', '1.3.4', :require => 'mingle_macro_models'
gem 'xmpp4r', '0.4' #This should probably be moved to development
gem 'activerecord-jdbc-adapter', '0.9.7', :require => 'jdbc_adapter', :path => 'vendor/gems/activerecord-jdbc-adapter-0.9.7', :platforms => :jruby
gem 'jvyaml', '~> 0.0.1', :require => 'jvyaml', :platforms => :jruby
gem 'ruby-net-ldap-SNAPSHOT', '0.0.4', :require => 'net/ldap', :path => 'vendor/gems/ruby-net-ldap-SNAPSHOT-0.0.4'
gem 'aws-sdk'
gem 'mingle-storage', '~> 0.0.13', :require => 'storage'
gem 'file_column_with_s3', '~> 0.1.9', :require => ['rails_file_column', 'file_compat']
gem 'will_paginate', '~> 2.3.16'
gem 'api-auth', '~> 1.0.3'
gem 'mixpanel-ruby', '1.0.1'
gem 'activerecord_partitioning'
gem 'sprockets', '~> 2.0'
gem 'sampling_prof'
gem 'json'
gem 'spymemcached.jruby'
gem 'histogram'
gem 'rails2_rubygems2_compatibility'
gem 'firebase_token_generator'
gem 'rack-rewrite'
gem 'rabl', '~> 0.13.1'
gem 'log4j', '0.1.0'
gem 'mingle-configuration', '~> 0.1.4'
gem 'stringex', '2.8.2'
gem 'elasticsearch'
group 'production' do
  gem 'honeybadger', :require => 'honeybadger/rails'
  gem 'wuparty', '~> 1.2.6'
end

group 'test', 'development' do
  gem 'warbler', '~> 1.4.9'
  gem 'ruby-debug-base'
  gem 'ruby-debug-ide', '0.6.0'
  gem 'jruby-jars', '1.7.25'
  gem 'jruby-rack', '1.1.20'
  gem 'rubyzip', '0.9.9'
  gem 'ci_reporter'
  gem 'racc', '1.4.5', :require => 'racc/grammar', :path => 'vendor/gems/racc-1.4.5'
  gem 'susy'
  gem 'compass-rails'
  gem 'sprockets-sass'
  gem 'sass', :require => 'sass'
  gem 'mocha', '0.9.7', :require => false
  gem 'tlb-core'
  gem 'bundle-audit'
  gem 'pry'
  gem 'pry-nav'
  gem 'jmx4r', :platforms => :jruby
  gem 'bourbon'
  gem 'selenium-rc-latest'
  gem 'rdoc', '2.4.2'
  gem 'timecop', '0.6.1' # this is the latest version that supports Ruby 1.8.7
  gem 'net-ssh', '~>2.9'

  gem 'tlb-testunit89', "0.3.4", :require => false
  gem 'test-unit', "1.2.3", :require => false
  gem 'addressable', '2.2.7'
  gem 'webmock', '1.16.1', :require => false
end

