#!/usr/bin/env ruby

# Copyright 2020 ThoughtWorks, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.

ENV['deactivate.features']="also_viewing"
require File.dirname(__FILE__) + '/../config/boot'
require 'disable_log_tailer'
require 'load_mingle_configuration'

java.lang.System.clearProperty("mingle.secureSiteURL")
java.lang.System.setProperty("mingle.siteURL", 'http://localhost:3000')

begin
  t = Thread.start do
    `memcached`
  end

  require 'commands/server'

rescue SystemExit, Interrupt
  `killall -KILL memcached`
  raise
end
